# coding: utf-8

default_platform(:ios)

platform :ios do

  before_all do |lane, options|
    skip_match = options[:skip_match] || true
    if !skip_match then
      provisioning_xcconfig
    end
    projectgen
    build_number = options[:build] || "1"
    increment_build_number(
      build_number: build_number,
      xcodeproj: "main.xcodeproj"
    )
  end

  lane :test do
    scan(scheme: "main", devices: ['iPhone 12'])
  end

  lane :local do |params|
    # FileUtils.mkdir_p("../main.xcworkspace/xcshareddata")
    # FileUtils.copy("IDETemplateMacros.plist", "../main.xcworkspace/xcshareddata/IDETemplateMacros.plist")
  end

  lane :verup do |params|
    increment_version_number(
      version_number: params[:version],
      xcodeproj: "main.xcodeproj"
    )
  end

  desc 'Archive binary with release build configuration for quality check and deploy ipa to DeployGate'
  lane :preview do |params|
    gym
  end

  lane :adhoc do |params|
    gym
  end


  after_all do |lane|
  end

  error do |lane, exception|
  end

end

